### ISSUE TITLE
Poor documentatin

### ISSUE THREAD

**Issue by hadmut** [lewisxhe/Esp-badge#1]
Hi, 
I own several of these epaper boards, but are not even sure, which ones. One (2.9, white) says "T5_v2.2 20181116", while the other (seems to be a 2.13 inch epaper board, looks like the one on the picture bottom left, but with four blue LEDs) does not even tell what it is. 

No clue about what the LEDs mean or how to use them, how to use the speaker, pin layout of the connector, or just even how to program them. The arduino IDE claims to program them, but nothing happens. No hint about which ESP32 board to select. 

While the board themselves seem to be technically good, the documentation is poor (worse: non-existing) and renders them more or less useless.

**Comment by lewisxhe** [comment]
> Hi,
> I own several of these epaper boards, but are not even sure, which ones. One (2.9, white) says "T5_v2.2 20181116", while the other (seems to be a 2.13 inch epaper board, looks like the one on the picture bottom left, but with four blue LEDs) does not even tell what it is.
> 
> No clue about what the LEDs mean or how to use them, how to use the speaker, pin layout of the connector, or just even how to program them. The arduino IDE claims to program them, but nothing happens. No hint about which ESP32 board to select.
> 
> While the board themselves seem to be technically good, the documentation is poor (worse: non-existing) and renders them more or less useless.

Hi hadmut,
I have already noticed that the information is incomplete. I am working hard to ask the team to improve it. At present, the repository I submitted contains pin descriptions and schematics. The library of lilygo was too messy. Now I am trying to perfect it. . You said the four led lights, like the lower left corner is the old version of the T5-V2.0, the four led are just the battery charging indicator, you can remove it if you don't need it.

**Comment by nano111** [comment]
Pinout on the board is wrong for version T5v2.2.
I have found 3 pins different,dont hav time to look further.
![ttgo_t5_pins](https://user-images.githubusercontent.com/38616454/57739536-45dfda80-76b4-11e9-9164-0a3fdd55101c.jpg)

**Comment by haldi4803** [comment]
Taken from the Schematic.... 
![grafik](https://user-images.githubusercontent.com/17104473/113485791-b0b87b80-94af-11eb-9d3b-6639f595288c.png)

p.S
E (517) gpio: io_num=34 can only be input
