### ISSUE TITLE
How to identify if GxGDE0213B72B is correct for my device

### ISSUE THREAD

**Issue by Heiner1967** [lewisxhe/Esp-badge#12]
Hi, as per your note GxGDE0213B72B is the latest, but hwo and where can I check on my T5 2.3 if I have a later or early Version and correspondingly decide if GxGDE0213B72B is correct for me?

Thanks for letting me know. ( May be good to extend your note with this piece of Information)

**Comment by lewisxhe** [comment]
The easiest is you look at the model behind the screen, if not then you can use any one for testing

**Comment by Heiner1967** [comment]
Many Thanks for the Info
