### ISSUE TITLE
instructions mention wrong file name

### ISSUE THREAD

**Issue by increpare** [lewisxhe/Esp-badge#17]
https://github.com/lewisxhe/TTGO-EPaper-Series/blob/master/README.MD

says

>For the first use, you need to select the model you are using at the top of main.cpp, and select the corresponding screen header file

but do you mean board_def.h rather than main.cpp?

**Comment by lewisxhe** [comment]
Is main.cpp, board_def.h has been deleted

**Comment by increpare** [comment]
Oh weird, must've been on the wrong version.  Sorry/thanks for the fast reply!
